### ISSUE TITLE
根本就不好使，按你的步骤

### ISSUE THREAD

**Issue by vwyuheng** [it-wwh/spring-cloud-gateway-oauth2#1]

**Comment by weigegeaa** [comment]
大哥  按照你上面的写法通过网关访问auth服务是可以了   但是怎么通过nginx代理的网关访问auth完成授权码过程     我通过nginx访问的id+ auth/oauth/authorize?client_id=social-security-card&response_type=code&scope=all&redirect_uri=http://www.baidu.com 跳转到登录页，登陆之后就报404了
